#!/bin/bash

/usr/bin/lxc-stop -n red
/usr/bin/lxc-stop -n green
/usr/bin/lxc-stop -n blue

sleep 3

/bin/cat > /var/lib/lxc/red/rootfs/etc/network/interfaces <<END
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 192.168.1.2
	netmask 255.255.255.0
	broadcast 192.168.1.255
	network 192.168.1.0
	gateway 192.168.1.1
	dns-nameservers 8.8.8.8
END

/bin/cat > /var/lib/lxc/green/rootfs/etc/network/interfaces <<END
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 192.168.2.2
	netmask 255.255.255.0
	broadcast 192.168.2.255
	network 192.168.2.0
	gateway 192.168.2.1
	dns-nameservers 8.8.8.8
END

/bin/cat > /var/lib/lxc/blue/rootfs/etc/network/interfaces <<END
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address 192.168.3.2
	netmask 255.255.255.0
	broadcast 192.168.3.255
	network 192.168.3.0
	gateway 192.168.3.1
	dns-nameservers 8.8.8.8
END

echo "nameserver 8.8.8.8" > /var/lib/lxc/red/rootfs/etc/resolv.conf
echo "nameserver 8.8.8.8" > /var/lib/lxc/green/rootfs/etc/resolv.conf
echo "nameserver 8.8.8.8" > /var/lib/lxc/blue/rootfs/etc/resolv.conf

/bin/cat > /var/lib/lxc/red/rootfs/etc/hosts <<END
127.0.0.1   localhost
192.168.1.2 red
192.168.2.2 green
192.168.3.2 blue
192.168.1.1 host

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
END

/bin/cat > /var/lib/lxc/green/rootfs/etc/hosts <<END
127.0.0.1   localhost
192.168.1.2 red
192.168.2.2 green
192.168.3.2 blue
192.168.2.1 host

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
END

/bin/cat > /var/lib/lxc/blue/rootfs/etc/hosts <<END
127.0.0.1   localhost
192.168.1.2 red
192.168.2.2 green
192.168.3.2 blue
192.168.3.1 host

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
END

/usr/bin/lxc-start -n red -d
/usr/bin/lxc-start -n green -d
/usr/bin/lxc-start -n blue -d

sleep 5

/sbin/ip a f dev veth-red
/sbin/ip a a 192.168.1.1/24 dev veth-red
/sbin/ip l s dev veth-red up

/sbin/ip a f dev veth-green
/sbin/ip a a 192.168.2.1/24 dev veth-green
/sbin/ip l s dev veth-green up

/sbin/ip a f dev veth-blue
/sbin/ip a a 192.168.3.1/24 dev veth-blue
/sbin/ip l s dev veth-blue up

/bin/cat > /etc/hosts <<END
127.0.0.1   localhost
127.0.1.1   host
192.168.1.2 red
192.168.2.2 green
192.168.3.2 blue

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouter
END

/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
/sbin/sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

# Install Apache2 on red and enable SSL.
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "apt-get -y install apache2 > /dev/null 2>&1" > /dev/null 2>&1
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "a2enmod ssl > /dev/null 2>&1"
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "a2ensite default-ssl > /dev/null 2>&1"
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "service apache2 restart > /dev/null 2>&1"
echo '<h1>Laborator 10 - pe red</h1>' > /var/lib/lxc/red/rootfs/var/www/index.html

# Generate file for red HTTP.
/bin/dd if=/dev/urandom of=/var/lib/lxc/red/rootfs/var/www/file.dat bs=1K count=1 > /dev/null 2>&1

# Create folder hierarchy for red.
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/mobile/Google/Nexus4/
echo "1.512 GHz quad-core Krait" > /var/lib/lxc/red/rootfs/var/www/folder/mobile/Google/Nexus4/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/mobile/Google/Nexus7/
echo "ARM Cortex-A9 Nvidia Tegra 3 T30L 1.2 GHz quad-core (1.3 GHz single-core mode) 1MB L2 cache" > /var/lib/lxc/red/rootfs/var/www/folder/mobile/Google/Nexus7/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/mobile/Apple/iPhone5S/
echo "1.3 GHz dual-core Apple-designed ARMv8-A 64-bit Apple A7 with M7 motion coprocessor" > /var/lib/lxc/red/rootfs/var/www/folder/mobile/Apple/iPhone5S/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/mobile/Apple/iPadAir/
echo "1.4 GHz dual-core Apple Cyclone" > /var/lib/lxc/red/rootfs/var/www/folder/mobile/Apple/iPadAir/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/embedded/Qualcomm/Scorpion/
echo "Single or dual-core configuration; 2.1 DMIPS/MHz" > /var/lib/lxc/red/rootfs/var/www/folder/embedded/Qualcomm/Scorpion/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/embedded/Qualcomm/Krait/
echo "Dual or quad-core configurations; 3.3 DMIPS/Mhz" > /var/lib/lxc/red/rootfs/var/www/folder/embedded/Qualcomm/Krait/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/embedded/TI/OMAP3/
echo "i1.2 GHz ARM Cortex-A8" > /var/lib/lxc/red/rootfs/var/www/folder/embedded/TI/OMAP3/info.txt
mkdir -p /var/lib/lxc/red/rootfs/var/www/folder/embedded/TI/OMAP4/
echo "1.3-1.5 GHz dual-core ARM Cortex-A9" > /var/lib/lxc/red/rootfs/var/www/folder/embedded/TI/OMAP4/info.txt

# Generate content for URL with special chars.
/bin/cat > /var/www/login.php <<END
<html>
<body>

Welcome <?php echo \$_GET["name"]; ?><br>
Your email address is: <?php echo \$_GET["email"]; ?>
</body>
</html>
END

# Create user `ana' on `red' using password `student'.
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "/usr/sbin/userdel -r ana > /dev/null 2>&1"
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "/usr/sbin/useradd -m -d /home/ana -s /bin/bash -l ana"
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "echo 'ana:student' | /usr/sbin/chpasswd"

# Add content for FTP download.
/bin/dd if=/dev/urandom of=/var/lib/lxc/red/rootfs/srv/ftp/download/file-10M.dat bs=1M count=10 > /dev/null 2>&1

/bin/dd if=/dev/urandom of=/var/lib/lxc/red/rootfs/home/ana/ana-ftp-file-5M.dat bs=1M count=5 > /dev/null 2>&1
/usr/bin/ssh -o StrictHostKeyChecking=no -l root red "/bin/chown ana:ana ~ana/ana-ftp-file-5M.dat" > /dev/null 2>&1

# Add users for e-mail message.
/usr/sbin/userdel -r bogdan > /dev/null 2>&1
/usr/sbin/useradd -m -d /home/bogdan -s /bin/bash -l bogdan
echo 'bogdan:student' | /usr/sbin/chpasswd
/usr/sbin/userdel -r corina > /dev/null 2>&1
/usr/sbin/useradd -m -d /home/corina -s /bin/bash -l corina
echo 'corina:student' | /usr/sbin/chpasswd

# Add content for FTP upload.
/bin/dd if=/dev/urandom of=/home/bogdan/bogdan-ftp-data-3M.dat bs=1M count=3 > /dev/null 2>&1
/bin/chown bogdan:bogdan ~bogdan/bogdan-ftp-data-3M.dat > /dev/null 2>&1
